import { db, serverTimestamp } from './firebase-core.js';
import { parseBits } from './parser.js';
import { doc,setDoc,collection,addDoc,getDocs,query,where,orderBy } from 'https://www.gstatic.com/firebasejs/10.12.4/firebase-firestore.js';
let questions=[];
const $=id=>document.getElementById(id);
$('loginBtn').onclick=()=>{ if($('pin').value==='1234'){ $('panel').classList.remove('hidden'); $('results').classList.remove('hidden'); $('examsBox').classList.remove('hidden'); $('loginBox').classList.add('hidden'); } else alert('Wrong PIN'); };
$('saveInstituteBtn').onclick=async()=>{ const code=$('instituteCode').value.trim().toUpperCase(), name=$('instituteName').value.trim(); if(!code||!name) return alert('Institute code/name kavali'); await setDoc(doc(db,'institutes',code),{code,name,active:true,createdAt:serverTimestamp()},{merge:true}); alert('Institute saved'); };
$('previewBtn').onclick=()=>{ questions=parseBits($('bits').value); renderPreview(); };
function renderPreview(){ $('preview').innerHTML=`<h3>Preview: ${questions.length} Questions</h3>`+questions.map((q,i)=>`<div class='qbox'><small>Q${i+1} Correct: ${q.correct}</small><textarea data-i='${i}' data-f='text'>${q.text}</textarea>${['A','B','C','D'].map(k=>`<input data-i='${i}' data-opt='${k}' placeholder='${k}' value='${(q.options.find(o=>o.key===k)||{}).text||''}'>`).join('')}<select data-i='${i}' data-f='correct'>${['A','B','C','D'].map(k=>`<option ${q.correct===k?'selected':''}>${k}</option>`).join('')}</select><button data-del='${i}' class='danger'>Delete</button></div>`).join('')+`<button id='addQ' class='secondary'>Add Question</button>`; document.querySelectorAll('[data-f],[data-opt]').forEach(el=>el.onchange=updateQ); document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{questions.splice(+b.dataset.del,1);renderPreview()}); $('addQ').onclick=()=>{questions.push({id:'q'+(questions.length+1),text:'New Question',options:['A','B','C','D'].map(k=>({key:k,text:''})),correct:'A',marks:1});renderPreview()}; }
function updateQ(e){ const i=+e.target.dataset.i; if(e.target.dataset.f==='text') questions[i].text=e.target.value; if(e.target.dataset.f==='correct') questions[i].correct=e.target.value; if(e.target.dataset.opt){ const k=e.target.dataset.opt; let o=questions[i].options.find(x=>x.key===k); if(!o){o={key:k,text:''};questions[i].options.push(o)} o.text=e.target.value; }}
$('saveExamBtn').onclick=async()=>{ const inst=$('instituteCode').value.trim().toUpperCase(), title=$('examTitle').value.trim(), start=$('startTime').value, end=$('endTime').value; if(!inst||!title||!start||!end||!questions.length) return alert('Institute, title, time, questions kavali'); const ref=await addDoc(collection(db,'exams'),{instituteCode:inst,title,startTime:new Date(start).toISOString(),endTime:new Date(end).toISOString(),status:'active',questionCount:questions.length,questions,createdAt:serverTimestamp()}); alert('Exam saved. Exam ID: '+ref.id); $('leaderExamId').value=ref.id; };
$('loadExamsBtn').onclick=async()=>{ const inst=$('filterInst').value.trim().toUpperCase(); const q=inst?query(collection(db,'exams'),where('instituteCode','==',inst)):query(collection(db,'exams')); const snap=await getDocs(q); $('examList').innerHTML=[...snap.docs].map(d=>{const x=d.data();return `<div class='qbox'><b>${x.title}</b><br><small>${x.instituteCode} | ${d.id}</small><br>${new Date(x.startTime).toLocaleString()} - ${new Date(x.endTime).toLocaleString()}<br><button onclick="document.getElementById('leaderExamId').value='${d.id}'">Use for Leaderboard</button></div>`}).join('')||'No exams'; };
$('loadLeaderBtn').onclick=loadLeaderboard; $('printBtn').onclick=()=>window.print();
async function loadLeaderboard(){ const examId=$('leaderExamId').value.trim(); if(!examId)return alert('Exam ID kavali'); const q=query(collection(db,'results'),where('examId','==',examId),orderBy('score','desc')); const snap=await getDocs(q); let rows=[...snap.docs].map((d,i)=>({rank:i+1,...d.data()})); $('leaderboard').innerHTML=`<table class='table'><tr><th>Rank</th><th>Name</th><th>Hall Ticket</th><th>Score</th><th>Total</th></tr>${rows.map(r=>`<tr><td>${r.rank}</td><td>${r.studentName}</td><td>${r.phone}</td><td>${r.score}</td><td>${r.total}</td></tr>`).join('')}</table>`; }
