import{auth,db,onAuthStateChanged,signOut,collection,getDocs,addDoc,doc,setDoc,serverTimestamp,$,show,esc}from'./app.js';
import{parseQuestions,blankQuestion}from'./parser.js';
let user=null,questions=[],previewIndex=0,lastCodes=[],lastExam=null;
const norm=v=>String(v||'').trim().toUpperCase();
onAuthStateChanged(auth,u=>{if(!u)location.href='login.html';else{user=u;setDefaultTimes();loadSavedExams();}});
$('logout').onclick=()=>signOut(auth);
function setDefaultTimes(){const now=new Date(),end=new Date(now.getTime()+2*60*60*1000),fmt=d=>{const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`};$('startTime').value=fmt(now);$('endTime').value=fmt(end)}
$('examId').addEventListener('input',()=>{$('examId').value=norm($('examId').value).replace(/\s+/g,'-')});
$('parseBtn').onclick=()=>{const parsed=parseQuestions($('rawBits').value,'General');if(!parsed.length)return show('Questions detect avvaledu. Format check cheyyandi.','err');questions=parsed;renderEditor();show(`${parsed.length} questions detected ✅`)};
$('addQuestionBtn').onclick=()=>{questions.push(blankQuestion('General'));renderEditor()};
function validate(){const issues=[];questions.forEach((q,i)=>{if(!q.question.trim())issues.push(`Q${i+1}: Question missing`);const filled=q.options.filter(o=>o.text.trim()).length;if(filled<4)issues.push(`Q${i+1}: ${4-filled} option(s) missing`);if(!['A','B','C','D'].includes(q.answer))issues.push(`Q${i+1}: Correct answer missing`)});const seen=new Map();questions.forEach((q,i)=>{const key=q.question.toLowerCase().replace(/\s+/g,' ').trim();if(key&&seen.has(key))issues.push(`Q${i+1}: Duplicate of Q${seen.get(key)+1}`);else seen.set(key,i)});return issues}
function renderHealth(){const issues=validate();$('health').innerHTML=`<b>Exam Health</b><div class="health-grid"><span>Questions: <b>${questions.length}</b></span><span>Issues: <b>${issues.length}</b></span><span>Status: <b class="${issues.length?'badText':'goodText'}">${questions.length&&!issues.length?'READY':'CHECK REQUIRED'}</b></span></div>${issues.length?`<details><summary>View Issues</summary><div class="issue-list">${issues.map(x=>`<div>${esc(x)}</div>`).join('')}</div></details>`:''}`;$('saveGenerateBtn').disabled=!questions.length||!!issues.length}
function renderEditor(){$('questionEditor').innerHTML=questions.map((q,i)=>`<div class="qcard"><div class="qhead"><b>Q${i+1}</b><div><button class="gray moveUp" data-i="${i}">↑</button><button class="gray moveDown" data-i="${i}">↓</button><button class="danger deleteQ" data-i="${i}">Delete</button></div></div><label>Question</label><textarea class="editQ" data-i="${i}">${esc(q.question)}</textarea><div class="grid two">${q.options.map((o,j)=>`<div><label>${o.key}) Option</label><input class="editOpt" data-i="${i}" data-j="${j}" value="${esc(o.text)}"></div>`).join('')}</div><label>Correct Answer</label><select class="editAns" data-i="${i}">${['A','B','C','D'].map(k=>`<option ${q.answer===k?'selected':''}>${k}</option>`).join('')}</select></div>`).join('');bindEditor();renderHealth()}
function sync(){document.querySelectorAll('.editQ').forEach(x=>questions[+x.dataset.i].question=x.value);document.querySelectorAll('.editOpt').forEach(x=>questions[+x.dataset.i].options[+x.dataset.j].text=x.value);document.querySelectorAll('.editAns').forEach(x=>questions[+x.dataset.i].answer=x.value)}
function bindEditor(){document.querySelectorAll('.editQ,.editOpt,.editAns').forEach(x=>x.oninput=()=>{sync();renderHealth()});document.querySelectorAll('.deleteQ').forEach(b=>b.onclick=()=>{questions.splice(+b.dataset.i,1);renderEditor()});document.querySelectorAll('.moveUp').forEach(b=>b.onclick=()=>{sync();const i=+b.dataset.i;if(i>0)[questions[i-1],questions[i]]=[questions[i],questions[i-1]];renderEditor()});document.querySelectorAll('.moveDown').forEach(b=>b.onclick=()=>{sync();const i=+b.dataset.i;if(i<questions.length-1)[questions[i+1],questions[i]]=[questions[i],questions[i+1]];renderEditor()})}
$('previewBtn').onclick=()=>{sync();if(!questions.length)return show('Preview ki questions levu.','err');previewIndex=0;$('previewCard').hidden=false;renderPreview();location.hash='previewCard'};
function renderPreview(){const q=questions[previewIndex];$('previewTitle').textContent=$('examTitle').value.trim()||$('examId').value.trim()||'Exam Preview';$('previewTimer').textContent=`${$('secondsPerQuestion').value||60} sec / Q`;$('previewContent').innerHTML=`<div class="questionText"><b>Question ${previewIndex+1} of ${questions.length}</b><h3>${esc(q.question).replace(/\n/g,'<br>')}</h3></div>${q.options.map(o=>`<label class="optionCard"><input type="radio" name="previewAnswer"><b>${o.key}</b><span>${esc(o.text)}</span></label>`).join('')}<div class="controls"><button class="gray" id="pPrev">Previous</button><button class="green" id="pNext">Save & Next</button></div>`;$('previewNav').innerHTML=questions.map((_,i)=>`<button class="pbtn ${i===previewIndex?'cur':'not'}" data-p="${i}">${i+1}</button>`).join('');document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{previewIndex=+b.dataset.p;renderPreview()});$('pPrev').onclick=()=>{if(previewIndex>0){previewIndex--;renderPreview()}};$('pNext').onclick=()=>{if(previewIndex<questions.length-1){previewIndex++;renderPreview()}}}
function makeCode(examId,i){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let r='';for(let n=0;n<6;n++)r+=chars[Math.floor(Math.random()*chars.length)];return `${examId}-${String(i+1).padStart(3,'0')}-${r}`}
$('saveGenerateBtn').onclick=async()=>{sync();const instituteName=$('instituteName').value.trim(),examPublicId=norm($('examId').value),title=$('examTitle').value.trim()||examPublicId,start=$('startTime').value,end=$('endTime').value,seconds=Math.max(5,Number($('secondsPerQuestion').value||60)),count=Math.max(1,Math.min(1000,Number($('codeCount').value||1))),issues=validate();if(!instituteName||!examPublicId||!start||!end)return show('Institute Name, Exam ID, Start Time, End Time enter cheyyandi.','err');if(Date.parse(end)<=Date.parse(start))return show('End Time, Start Time తర్వాత ఉండాలి.','err');if(issues.length||!questions.length)return show('Questions lo issues fix cheyyandi.','err');$('saveGenerateBtn').disabled=true;try{const all=await getDocs(collection(db,'exams'));let duplicate=false;all.forEach(d=>{if(norm(d.data().examId||d.data().examCode)===examPublicId)duplicate=true});if(duplicate)return show('Ee Exam ID already undi. Vere Exam ID use cheyyandi.','err');const totalSeconds=seconds*questions.length;const examRef=await addDoc(collection(db,'exams'),{instituteName,instituteCode:instituteName,title,examId:examPublicId,examCode:examPublicId,startTime:new Date(start).toISOString(),endTime:new Date(end).toISOString(),start:new Date(start).toISOString(),end:new Date(end).toISOString(),secondsPerQuestion:seconds,totalMinutes:Math.ceil(totalSeconds/60),status:$('status').value,questionCount:questions.length,allowPrevious:true,shuffleQuestions:false,shuffleOptions:false,createdBy:user.email,createdAt:serverTimestamp()});await setDoc(doc(db,'examQuestions',examRef.id),{examId:examRef.id,questions,questionCount:questions.length,updatedAt:serverTimestamp()});lastCodes=[];for(let i=0;i<count;i++){let code=makeCode(examPublicId,i),ref=await addDoc(collection(db,'studentAccess'),{examId:examRef.id,examPublicId,code,status:'unused',studentName:'',mobile:'',createdAt:serverTimestamp()});lastCodes.push({id:ref.id,code,status:'unused'})}lastExam={docId:examRef.id,examId:examPublicId,title,instituteName};$('resultExamId').value=examPublicId;renderCodes();show(`Exam saved ✅ ${count} codes generated.`);loadSavedExams()}catch(e){show(e.message,'err')}finally{$('saveGenerateBtn').disabled=false;renderHealth()}};
function renderCodes(){$('codesBox').innerHTML=lastCodes.length?`<div class="print-header"><h2>${esc(lastExam?.instituteName||'')}</h2><h3>${esc(lastExam?.title||'')}</h3><p>Exam ID: <b>${esc(lastExam?.examId||'')}</b></p></div><table class="table"><tr><th>No.</th><th>Exam Code</th><th>Status</th></tr>${lastCodes.map((x,i)=>`<tr><td>${i+1}</td><td><b>${esc(x.code)}</b></td><td>${esc(x.status)}</td></tr>`).join('')}</table>`:'<p>No codes</p>'}
$('copyCodes').onclick=async()=>{if(!lastCodes.length)return show('Codes levu.','err');await navigator.clipboard.writeText(`Exam ID: ${lastExam.examId}\n`+lastCodes.map(x=>x.code).join('\n'));show('Exam ID + Codes copied ✅')};
$('printCodes').onclick=()=>{if(!lastCodes.length)return show('Codes levu.','err');printSection('codesBox','Generated Exam Codes')};
$('loadResults').onclick=loadResults;$('printResults').onclick=()=>printSection('resultsBox','Exam Results & Ranks');
async function loadResults(){const publicId=norm($('resultExamId').value);if(!publicId)return show('Results kosam Exam ID enter cheyyandi.','err');let examDocId='';const exams=await getDocs(collection(db,'exams'));exams.forEach(d=>{if(norm(d.data().examId||d.data().examCode)===publicId)examDocId=d.id});if(!examDocId)return show('Exam ID dorakaledu.','err');const snap=await getDocs(collection(db,'results'));let rows=[];snap.forEach(d=>{const r=d.data();if(r.examId===examDocId)rows.push(r)});rows.sort((a,b)=>(b.score-a.score)||((a.totalTime||999999)-(b.totalTime||999999))||String(a.name||'').localeCompare(String(b.name||'')));let rank=0,lastScore=null;rows=rows.map((r,i)=>{if(r.score!==lastScore)rank=i+1;lastScore=r.score;return{...r,rank}});$('resultsBox').innerHTML=rows.length?`<div class="print-header"><h2>Results</h2><p>Exam ID: <b>${esc(publicId)}</b></p></div><table class="table"><tr><th>Rank</th><th>Name</th><th>Exam Code</th><th>Phone</th><th>Score</th><th>Total</th></tr>${rows.map(r=>`<tr><td><b>${r.rank}</b></td><td>${esc(r.name||r.studentName||'-')}</td><td>${esc(r.studentCode||r.examCode||'-')}</td><td>${esc(r.phone||'-')}</td><td><b>${Number(r.score||0)}</b></td><td>${Number(r.total||0)}</td></tr>`).join('')}</table>`:'<p class="msg warn">No results yet.</p>'}
function printSection(id,title){const el=$(id);if(!el||!el.innerHTML.trim())return show('Print cheyyadaniki data ledu.','err');const w=window.open('','_blank');w.document.write(`<html><head><title>${esc(title)}</title><link rel="stylesheet" href="style.css"><style>body{padding:24px}.table{width:100%;border-collapse:collapse}.table th,.table td{border:1px solid #aaa;padding:8px;text-align:left}@media print{button{display:none}}</style></head><body><h1>${esc(title)}</h1>${el.innerHTML}<script>setTimeout(()=>window.print(),400)<\/script></body></html>`);w.document.close()}
$('refreshExams').onclick=loadSavedExams;async function loadSavedExams(){const snap=await getDocs(collection(db,'exams'));let arr=[];snap.forEach(d=>arr.push({id:d.id,...d.data()}));arr.sort((a,b)=>String(b.createdAt?.seconds||0).localeCompare(String(a.createdAt?.seconds||0)));$('savedExams').innerHTML=arr.map(e=>`<div class="qcard"><b>${esc(e.title||e.examId||'Exam')}</b><p>Exam ID: <b>${esc(e.examId||e.examCode||e.id)}</b></p><p>${esc(e.instituteName||'')} • Questions: ${Number(e.questionCount||0)} • Status: ${esc(e.status||'')}</p><div class="action-row"><button class="gray useResult" data-id="${esc(e.examId||e.examCode||'')}">View Results</button></div></div>`).join('')||'<p>No exams</p>';document.querySelectorAll('.useResult').forEach(b=>b.onclick=()=>{$('resultExamId').value=b.dataset.id;loadResults();location.hash='resultsBox'})}
