const ADMIN_PIN='1234'; let questions=[];
function login(){if(document.getElementById('pin').value===ADMIN_PIN){loginBox(false);renderAll()}else alert('Wrong PIN')}
function loginBox(show){document.getElementById('login').classList.toggle('hidden',!show);document.getElementById('app').classList.toggle('hidden',show)}
function parseNow(){questions=parseBits(document.getElementById('bulk').value);let m=Number(document.getElementById('marks').value)||1;questions.forEach(q=>q.marks=m);renderPreview();}
function renderPreview(){let out='';document.getElementById('qcount').textContent=questions.length+' Questions';questions.forEach((q,i)=>{out+=`<div class="qbox"><div class="qhead"><b>Q${i+1}</b><div><button class="btn light" onclick="moveQ(${i},-1)">↑</button> <button class="btn light" onclick="moveQ(${i},1)">↓</button> <button class="btn red" onclick="delQ(${i})">Delete</button></div></div><label>Question</label><textarea onchange="questions[${i}].question=this.value">${esc(q.question)}</textarea><div class="grid">${['A','B','C','D'].map(k=>`<div><label>${k}</label><input value="${esc(q.options[k])}" onchange="questions[${i}].options['${k}']=this.value"></div>`).join('')}</div><div class="grid"><div><label>Correct Answer</label><select onchange="questions[${i}].answer=this.value">${['A','B','C','D'].map(k=>`<option ${q.answer===k?'selected':''}>${k}</option>`).join('')}</select></div><div><label>Marks</label><input type="number" value="${q.marks||1}" onchange="questions[${i}].marks=Number(this.value)||1"></div></div></div>`});document.getElementById('preview').innerHTML=out||'<p class="small">No questions yet.</p>'}
function esc(s){return String(s||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function addQuestion(){questions.push({question:'',options:{A:'',B:'',C:'',D:''},answer:'A',marks:Number(document.getElementById('marks').value)||1});renderPreview()}
function delQ(i){if(confirm('Delete this question?')){questions.splice(i,1);renderPreview()}}
function moveQ(i,d){let j=i+d;if(j<0||j>=questions.length)return;[questions[i],questions[j]]=[questions[j],questions[i]];renderPreview()}
function saveExam(){if(!questions.length)return alert('Questions add cheyyi');let exams=getExams();let id=document.getElementById('editId').value||uid();let exam={id,institute:inst.value||'KSR Institute',title:title.value||'DSC Exam',start:start.value,end:end.value,duration:Number(duration.value)||150,instructions:instructions.value,questions,active:true,createdAt:new Date().toISOString()};let idx=exams.findIndex(e=>e.id===id);if(idx>=0)exams[idx]=exam;else exams.push(exam);setExams(exams);alert('Exam saved');clearForm();renderAll()}
function clearForm(){editId.value='';title.value='';bulk.value='';questions=[];renderPreview()}
function editExam(id){let e=getExams().find(x=>x.id===id);if(!e)return;editId.value=e.id;inst.value=e.institute;title.value=e.title;start.value=e.start||'';end.value=e.end||'';duration.value=e.duration;instructions.value=e.instructions;questions=JSON.parse(JSON.stringify(e.questions));renderPreview();scrollTo(0,0)}
function deleteExam(id){if(confirm('Delete exam and keep old results?')){setExams(getExams().filter(e=>e.id!==id));renderAll()}}
function toggleExam(id){let ex=getExams();let e=ex.find(x=>x.id===id);e.active=!e.active;setExams(ex);renderAll()}
function renderExams(){let exams=getExams();examList.innerHTML=exams.map(e=>`<div class="qbox"><b>${esc(e.title)}</b> <span class="pill">${e.questions.length} Q</span> <span class="pill">${e.active?'Active':'Inactive'}</span><p>${esc(e.institute)}</p><button class="btn" onclick="editExam('${e.id}')">Edit</button> <button class="btn orange" onclick="toggleExam('${e.id}')">${e.active?'Deactivate':'Activate'}</button> <button class="btn red" onclick="deleteExam('${e.id}')">Delete</button></div>`).join('')||'No exams saved.'}
function renderResults(){let res=getResults().sort((a,b)=>b.score-a.score||a.timeTaken-b.timeTaken);let rows=res.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.name)}</td><td>${esc(r.examTitle)}</td><td>${r.score}/${r.total}</td><td>${r.percent}%</td><td>${new Date(r.submittedAt).toLocaleString()}</td></tr>`).join('');results.innerHTML=`<table class="table"><tr><th>Rank</th><th>Name</th><th>Exam</th><th>Marks</th><th>%</th><th>Date</th></tr>${rows}</table>`}
function renderAll(){renderPreview();renderExams();renderResults()} window.onload=()=>{};
