import { db, serverTimestamp } from './firebase-core.js';
import { doc,getDoc,setDoc,collection,query,where,getDocs } from 'https://www.gstatic.com/firebasejs/10.12.4/firebase-firestore.js';
const $=id=>document.getElementById(id); const params=new URLSearchParams(location.search); const examId=params.get('examId'); let exam, student, answers={}, idx=0, timer;
init();
async function init(){ student=JSON.parse(localStorage.getItem('ksrStudent')||'{}'); if(!student.phone) return location.href='index.html'; const dupQ=query(collection(db,'results'),where('examId','==',examId),where('phone','==',student.phone)); if(!(await getDocs(dupQ)).empty){ alert('Already submitted'); return location.href='result.html?examId='+examId+'&phone='+encodeURIComponent(student.phone); } const snap=await getDoc(doc(db,'exams',examId)); if(!snap.exists()) return alert('Exam not found'); exam={id:snap.id,...snap.data()}; $('instName').textContent=exam.instituteCode; $('examTitle').textContent=exam.title; const saved=JSON.parse(localStorage.getItem('ans_'+examId+'_'+student.phone)||'{}'); answers=saved; render(); startTimer(); }
function render(){ const q=exam.questions[idx]; $('qno').textContent=`Question ${idx+1} / ${exam.questions.length}`; $('qtext').textContent=q.text; $('opts').innerHTML=q.options.map(o=>`<label class='option'><input type='radio' name='opt' value='${o.key}' ${answers[q.id]===o.key?'checked':''}> ${o.key}. ${o.text}</label>`).join(''); document.querySelectorAll('input[name=opt]').forEach(r=>r.onchange=()=>{answers[q.id]=r.value; saveLocal(); renderPalette();}); renderPalette(); }
function renderPalette(){ $('palette').innerHTML='<h3>Questions</h3>'+exam.questions.map((q,i)=>`<button class='palbtn ${answers[q.id]?'ans':''} ${i===idx?'cur':''}' data-i='${i}'>${i+1}</button>`).join('')+'<p class="notice">Green = Answered</p>'; document.querySelectorAll('.palbtn').forEach(b=>b.onclick=()=>{idx=+b.dataset.i;render()}); }
function saveLocal(){ localStorage.setItem('ans_'+examId+'_'+student.phone,JSON.stringify(answers)); }
$('prevBtn').onclick=()=>{ if(idx>0){idx--;render()} }; $('nextBtn').onclick=()=>{ if(idx<exam.questions.length-1){idx++;render()} }; $('submitBtn').onclick=()=>{ if(confirm('Submit cheyyala?')) submitExam(); };
async function submitExam(){ clearInterval(timer); let score=0; const details=exam.questions.map((q,i)=>{const a=answers[q.id]||''; const ok=a===q.correct; if(ok) score+=(q.marks||1); return {no:i+1,question:q.text,selected:a,correct:q.correct,isCorrect:ok};}); const total=exam.questions.reduce((s,q)=>s+(q.marks||1),0); const id=examId+'_'+student.phone.replace(/\W/g,''); await setDoc(doc(db,'results',id),{examId,instituteCode:exam.instituteCode,examTitle:exam.title,studentName:student.name,phone:student.phone,answers,details,score,total,submittedAt:serverTimestamp()}); location.href='result.html?examId='+examId+'&phone='+encodeURIComponent(student.phone); }
function startTimer(){ timer=setInterval(()=>{ const left=Date.parse(exam.endTime)-Date.now(); if(left<=0){ submitExam(); return; } const m=Math.floor(left/60000), s=Math.floor((left%60000)/1000); $('timer').textContent=`${m}:${String(s).padStart(2,'0')}`; },1000); }
