import{auth,db,onAuthStateChanged,signOut,collection,getDocs,addDoc,doc,setDoc,deleteDoc,serverTimestamp,$,show,esc}from'./app.js';
let institutes=[],batches=[],students=[],user=null;
onAuthStateChanged(auth,u=>{if(!u)location.href='login.html';else{user=u;loadAll()}});$('logout').onclick=()=>signOut(auth);
const toast=(m,t='ok')=>show(m,t);
$('saveInst').onclick=async()=>{const name=$('instName').value.trim(),logoUrl=$('instLogo').value.trim();if(!name)return toast('Institute name enter cheyyandi','err');await addDoc(collection(db,'institutes'),{name,logoUrl,active:true,createdBy:user.email,createdAt:serverTimestamp()});$('instName').value='';$('instLogo').value='';toast('Institute saved ✅');loadAll()};
$('saveBatch').onclick=async()=>{const instituteId=$('batchInst').value,name=$('batchName').value.trim();if(!instituteId||!name)return toast('Institute, Batch Name compulsory','err');await addDoc(collection(db,'batches'),{instituteId,name,active:true,createdBy:user.email,createdAt:serverTimestamp()});$('batchName').value='';toast('Batch saved ✅');loadAll()};
$('studentInst').onchange=renderStudentBatches;$('batchInst').onchange=renderBatches;
$('addStudent').onclick=()=>saveStudent($('studentName').value.trim(),$('studentRoll').value.trim());
$('clearStudent').onclick=()=>{$('studentName').value='';$('studentRoll').value=''};
$('bulkAdd').onclick=async()=>{const names=$('bulkStudents').value.split(/\n+/).map(x=>x.trim()).filter(Boolean);if(!names.length)return toast('Names paste cheyyandi','err');for(const name of names)await saveStudent(name,'',false);$('bulkStudents').value='';toast(`${names.length} students added ✅`);loadStudents()};
async function saveStudent(name,roll='',refresh=true){const instituteId=$('studentInst').value,batchId=$('studentBatch').value;if(!instituteId||!batchId||!name)return toast('Institute, Batch, Student Name compulsory','err');await addDoc(collection(db,'studentMaster'),{instituteId,batchId,name,roll,active:true,createdBy:user.email,createdAt:serverTimestamp()});if(refresh){$('studentName').value='';$('studentRoll').value='';toast('Student added ✅');loadStudents()}}
$('loadStudents').onclick=loadStudents;$('studentSearch').oninput=renderStudents;
async function loadAll(){const [is,bs]=await Promise.all([getDocs(collection(db,'institutes')),getDocs(collection(db,'batches'))]);institutes=[];batches=[];is.forEach(d=>institutes.push({id:d.id,...d.data()}));bs.forEach(d=>batches.push({id:d.id,...d.data()}));institutes.sort((a,b)=>String(a.name).localeCompare(String(b.name)));batches.sort((a,b)=>String(a.name).localeCompare(String(b.name)));renderMasters();}
function renderMasters(){const opts=institutes.map(i=>`<option value="${i.id}">${esc(i.name)}</option>`).join('');$('batchInst').innerHTML=opts;$('studentInst').innerHTML=opts;$('instList').innerHTML=institutes.map(i=>`<div class="masterRow"><div>${i.logoUrl?`<img src="${esc(i.logoUrl)}" class="miniLogo">`:''}<b>${esc(i.name)}</b></div><button class="danger delInst" data-id="${i.id}">Delete</button></div>`).join('')||'<p class="small">No institutes</p>';document.querySelectorAll('.delInst').forEach(b=>b.onclick=async()=>{if(!confirm('Delete institute? First related batches/students delete cheyyandi.'))return;await deleteDoc(doc(db,'institutes',b.dataset.id));loadAll()});renderBatches();renderStudentBatches()}
function renderBatches(){const id=$('batchInst').value;const arr=batches.filter(b=>b.instituteId===id);$('batchList').innerHTML=arr.map(b=>`<div class="masterRow"><b>${esc(b.name)}</b><button class="danger delBatch" data-id="${b.id}">Delete</button></div>`).join('')||'<p class="small">No batches</p>';document.querySelectorAll('.delBatch').forEach(b=>b.onclick=async()=>{if(!confirm('Delete batch?'))return;await deleteDoc(doc(db,'batches',b.dataset.id));loadAll()})}
function renderStudentBatches(){const id=$('studentInst').value;const arr=batches.filter(b=>b.instituteId===id);$('studentBatch').innerHTML=arr.map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('')}
async function loadStudents(){const snap=await getDocs(collection(db,'studentMaster'));students=[];snap.forEach(d=>students.push({id:d.id,...d.data()}));renderStudents()}
function renderStudents(){const batchId=$('studentBatch').value,q=$('studentSearch').value.trim().toLowerCase();const arr=students.filter(s=>s.batchId===batchId&&(!q||[s.name,s.roll].some(v=>String(v||'').toLowerCase().includes(q))));$('studentList').innerHTML=`<p class="small"><b>${arr.length}</b> students</p>`+arr.map((s,i)=>`<div class="masterRow"><span>${i+1}. <b>${esc(s.name)}</b>${s.roll?` • ${esc(s.roll)}`:''}</span><button class="danger delStudent" data-id="${s.id}">Delete</button></div>`).join('');document.querySelectorAll('.delStudent').forEach(b=>b.onclick=async()=>{if(!confirm('Delete student?'))return;await deleteDoc(doc(db,'studentMaster',b.dataset.id));loadStudents()})}
