import{auth,db,onAuthStateChanged,signOut,collection,getDocs,addDoc,doc,updateDoc,deleteDoc,serverTimestamp,$,show,esc}from'./app.js';
let institutes=[],batches=[],students=[],contacts=[],user=null,selectedInstitute='',selectedBatch='';
onAuthStateChanged(auth,u=>{if(!u)location.href='login.html';else{user=u;loadAll()}});$('logout').onclick=()=>signOut(auth);
const toast=(m,t='ok')=>show(m,t);
const instById=id=>institutes.find(x=>x.id===id)||{};const batchById=id=>batches.find(x=>x.id===id)||{};

$('showMasterBtn').onclick=()=>toggle('masterPanel',true);$('closeMasterBtn').onclick=()=>toggle('masterPanel',false);
$('showContactsBtn').onclick=async()=>{toggle('contactsPanel',true);await loadContacts()};$('closeContactsBtn').onclick=()=>toggle('contactsPanel',false);
$('openAddStudent').onclick=()=>{if(!selectedBatch)return toast('Mundhu batch select cheyyandi','err');$('addStudentContext').textContent=`${instById(selectedInstitute).name||''} → ${batchById(selectedBatch).name||''}`;toggle('addStudentPanel',true)};
$('closeAddStudent').onclick=()=>toggle('addStudentPanel',false);
function toggle(id,on){$(id).hidden=!on;if(on)$(id).scrollIntoView({behavior:'smooth',block:'start'})}

$('saveInst').onclick=async()=>{const name=$('instName').value.trim(),logoUrl=$('instLogo').value.trim();if(!name)return toast('Institute name enter cheyyandi','err');await addDoc(collection(db,'institutes'),{name,logoUrl,active:true,createdBy:user.email,createdAt:serverTimestamp()});$('instName').value='';$('instLogo').value='';toast('Institute saved ✅');loadAll()};
$('saveBatch').onclick=async()=>{const instituteId=$('batchInst').value,name=$('batchName').value.trim();if(!instituteId||!name)return toast('Institute, Batch Name compulsory','err');await addDoc(collection(db,'batches'),{instituteId,name,active:true,createdBy:user.email,createdAt:serverTimestamp()});$('batchName').value='';toast('Batch saved ✅');loadAll()};
$('batchInst').onchange=renderMasterBatches;

$('addStudent').onclick=()=>saveStudent({name:$('studentName').value.trim(),phone:$('studentPhone').value.trim(),roll:$('studentRoll').value.trim(),status:$('studentStatus').value});
$('clearStudent').onclick=clearStudentForm;
$('bulkAdd').onclick=async()=>{if(!selectedInstitute||!selectedBatch)return toast('Institute and batch select cheyyandi','err');const rows=$('bulkStudents').value.split(/\n+/).map(x=>x.trim()).filter(Boolean);if(!rows.length)return toast('Students paste cheyyandi','err');let added=0;for(const row of rows){const [name='',phone='',roll='']=row.split(',').map(x=>x.trim());if(name){await saveStudent({name,phone,roll,status:'active'},false);added++}}$('bulkStudents').value='';toast(`${added} students added ✅`);await loadStudents()};
async function saveStudent(data,refresh=true){if(!selectedInstitute||!selectedBatch||!data.name)return toast('Institute, Batch, Student Name compulsory','err');if(data.phone&&!/^\d{10}$/.test(data.phone))return toast('Phone number 10 digits undali','err');await addDoc(collection(db,'studentMaster'),{instituteId:selectedInstitute,batchId:selectedBatch,name:data.name,phone:data.phone||'',roll:data.roll||'',status:data.status||'active',active:(data.status||'active')==='active',createdBy:user.email,createdAt:serverTimestamp()});if(refresh){clearStudentForm();toast('Student saved ✅');await loadStudents()}}
function clearStudentForm(){$('studentName').value='';$('studentPhone').value='';$('studentRoll').value='';$('studentStatus').value='active'}

$('loadStudents').onclick=loadStudents;$('studentSearch').oninput=renderStudents;$('statusFilter').onchange=renderStudents;
async function loadAll(){const [is,bs]=await Promise.all([getDocs(collection(db,'institutes')),getDocs(collection(db,'batches'))]);institutes=[];batches=[];is.forEach(d=>institutes.push({id:d.id,...d.data()}));bs.forEach(d=>batches.push({id:d.id,...d.data()}));institutes.sort(sortName);batches.sort(sortName);if(selectedInstitute&&!institutes.some(i=>i.id===selectedInstitute)){selectedInstitute='';selectedBatch=''}renderHierarchy();renderMasters();renderContactFilters()}
const sortName=(a,b)=>String(a.name||'').localeCompare(String(b.name||''));
function renderHierarchy(){$('instituteCards').innerHTML=institutes.map(i=>`<button type="button" class="choiceCard ${selectedInstitute===i.id?'selected':''}" data-inst="${i.id}">${i.logoUrl?`<img src="${esc(i.logoUrl)}" alt="">`:'<span class="choiceIcon">🏫</span>'}<b>${esc(i.name)}</b></button>`).join('')||'<p class="small">No institutes. + Institute / Batch nokkandi.</p>';document.querySelectorAll('[data-inst]').forEach(b=>b.onclick=()=>{selectedInstitute=b.dataset.inst;selectedBatch='';renderHierarchy();renderBatchChoices();$('studentPanel').hidden=true;$('addStudentPanel').hidden=true});renderBatchChoices()}
function renderBatchChoices(){const arr=batches.filter(b=>b.instituteId===selectedInstitute);$('batchCards').innerHTML=selectedInstitute?(arr.map(b=>`<button type="button" class="choiceCard batchChoice ${selectedBatch===b.id?'selected':''}" data-batch="${b.id}"><span class="choiceIcon">👥</span><b>${esc(b.name)}</b></button>`).join('')||'<p class="small">Ee institute lo batches levu.</p>'):'<p class="small">Institute select cheyyandi.</p>';document.querySelectorAll('[data-batch]').forEach(b=>b.onclick=async()=>{selectedBatch=b.dataset.batch;renderHierarchy();$('hierarchySummary').innerHTML=`<b>${esc(instById(selectedInstitute).name||'')}</b> → <b>${esc(batchById(selectedBatch).name||'')}</b>`;$('studentPanelTitle').textContent=batchById(selectedBatch).name+' Students';$('studentPanelSub').textContent=instById(selectedInstitute).name||'';$('studentPanel').hidden=false;await loadStudents();$('studentPanel').scrollIntoView({behavior:'smooth',block:'start'})})}

async function loadStudents(){if(!selectedBatch)return;const snap=await getDocs(collection(db,'studentMaster'));students=[];snap.forEach(d=>{const x={id:d.id,...d.data()};if(x.batchId===selectedBatch)students.push(x)});students.sort(sortName);renderStudents()}
function renderStudents(){const q=$('studentSearch').value.trim().toLowerCase(),status=$('statusFilter').value;const arr=students.filter(s=>(status==='all'||(s.status||((s.active===false)?'inactive':'active'))===status)&&(!q||[s.name,s.phone,s.roll].some(v=>String(v||'').toLowerCase().includes(q))));$('studentList').innerHTML=`<div class="listSummary"><b>${arr.length}</b> students</div>`+(arr.map((s,i)=>{const st=s.status||((s.active===false)?'inactive':'active');return `<div class="studentRow"><div class="studentMain"><span class="serial">${i+1}</span><div><b>${esc(s.name)}</b><small>${s.phone?esc(s.phone):'No phone'}${s.roll?' • '+esc(s.roll):''}</small></div></div><div class="studentActions"><select class="statusSelect" data-status-id="${s.id}"><option value="active" ${st==='active'?'selected':''}>Active</option><option value="hold" ${st==='hold'?'selected':''}>On Hold</option><option value="inactive" ${st==='inactive'?'selected':''}>Inactive</option></select><button class="danger delStudent" data-id="${s.id}">Delete</button></div></div>`}).join('')||'<p class="small">Ee filter lo students leru.</p>');document.querySelectorAll('[data-status-id]').forEach(el=>el.onchange=async()=>{await updateDoc(doc(db,'studentMaster',el.dataset.statusId),{status:el.value,active:el.value==='active',updatedAt:serverTimestamp()});toast('Student status updated ✅');await loadStudents()});document.querySelectorAll('.delStudent').forEach(b=>b.onclick=async()=>{if(!confirm('Student ni permanent ga delete cheyyala? On Hold option better.'))return;await deleteDoc(doc(db,'studentMaster',b.dataset.id));toast('Student deleted');loadStudents()})}

function renderMasters(){const opts=institutes.map(i=>`<option value="${i.id}">${esc(i.name)}</option>`).join('');$('batchInst').innerHTML=opts;$('instList').innerHTML=institutes.map(i=>`<div class="masterRow"><div>${i.logoUrl?`<img src="${esc(i.logoUrl)}" class="miniLogo">`:''}<b>${esc(i.name)}</b></div><button class="danger delInst" data-id="${i.id}">Delete</button></div>`).join('')||'<p class="small">No institutes</p>';document.querySelectorAll('.delInst').forEach(b=>b.onclick=async()=>{if(batches.some(x=>x.instituteId===b.dataset.id))return toast('Mundhu related batches remove cheyyandi','err');if(!confirm('Delete institute?'))return;await deleteDoc(doc(db,'institutes',b.dataset.id));loadAll()});renderMasterBatches()}
function renderMasterBatches(){const id=$('batchInst').value,arr=batches.filter(b=>b.instituteId===id);$('batchList').innerHTML=arr.map(b=>`<div class="masterRow"><b>${esc(b.name)}</b><button class="danger delBatch" data-id="${b.id}">Delete</button></div>`).join('')||'<p class="small">No batches</p>';document.querySelectorAll('.delBatch').forEach(b=>b.onclick=async()=>{if(!confirm('Delete batch? Students history kosam On Hold use cheyyadam better.'))return;await deleteDoc(doc(db,'batches',b.dataset.id));loadAll()})}

async function loadContacts(){const snap=await getDocs(collection(db,'results'));const map=new Map();snap.forEach(d=>{const r={id:d.id,...d.data()},phone=String(r.phone||'').trim();if(!phone)return;const key=(r.name||'').toLowerCase()+'|'+phone;const old=map.get(key);if(!old||toMillis(r.submittedAt)>toMillis(old.submittedAt))map.set(key,r)});contacts=[...map.values()].sort((a,b)=>String(a.name||'').localeCompare(String(b.name||'')));renderContacts()}
function toMillis(v){return v?.toMillis?v.toMillis():0}
$('contactSearch').oninput=renderContacts;$('contactInstitute').onchange=renderContacts;$('contactBatch').onchange=renderContacts;
function renderContactFilters(){$('contactInstitute').innerHTML='<option value="all">All Institutes</option>'+institutes.map(i=>`<option value="${i.id}">${esc(i.name)}</option>`).join('');$('contactBatch').innerHTML='<option value="all">All Batches</option>'+batches.map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('')}
function filteredContacts(){const q=$('contactSearch').value.trim().toLowerCase(),ii=$('contactInstitute').value,bb=$('contactBatch').value;return contacts.filter(r=>(ii==='all'||r.instituteId===ii)&&(bb==='all'||r.batchId===bb)&&(!q||[r.name,r.phone,r.examCode,r.batchName].some(v=>String(v||'').toLowerCase().includes(q))))}
function renderContacts(){const arr=filteredContacts();$('contactList').innerHTML=`<div class="listSummary"><b>${arr.length}</b> unique contacts</div><div class="contactTableWrap"><table class="contactTable"><thead><tr><th>S.No</th><th>Name</th><th>Phone</th><th>Institute</th><th>Batch</th><th>Last Exam</th></tr></thead><tbody>${arr.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.name||'Student')}</td><td>${esc(r.phone||'')}</td><td>${esc(instById(r.instituteId).name||r.instituteCode||'-')}</td><td>${esc(batchById(r.batchId).name||r.batchName||'-')}</td><td>${esc(r.examCode||r.examId||'-')}</td></tr>`).join('')}</tbody></table></div>`}
$('printContacts').onclick=()=>{const arr=filteredContacts();if(!arr.length)return toast('Contacts levu','err');const w=window.open('','_blank');w.document.write(`<html><head><title>KSR Contact List</title><style>body{font-family:Arial;padding:24px}h1{color:#0b2b63}table{width:100%;border-collapse:collapse}th,td{border:1px solid #bbb;padding:8px;text-align:left}th{background:#0b2b63;color:white}.note{color:#666;font-size:12px}</style></head><body><h1>KSR Online Exams</h1><h2>Student Contact List</h2><p class="note">Admin use only. Public results PDF lo phone numbers include cheyyakandi.</p><table><tr><th>S.No</th><th>Name</th><th>Phone</th><th>Institute</th><th>Batch</th><th>Last Exam</th></tr>${arr.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.name||'')}</td><td>${esc(r.phone||'')}</td><td>${esc(instById(r.instituteId).name||'-')}</td><td>${esc(batchById(r.batchId).name||r.batchName||'-')}</td><td>${esc(r.examCode||r.examId||'-')}</td></tr>`).join('')}</table></body></html>`);w.document.close();setTimeout(()=>w.print(),300)};
