import{auth,db,onAuthStateChanged,signOut,collection,getDocs,doc,setDoc,deleteDoc,serverTimestamp,writeBatch,$,show,esc}from'./app.js';
import{parseQuestions}from'./parser.js';
let parsed=[],all=[];
const clean=v=>String(v||'').trim();
const folder=v=>clean(v)||'General';
function hashText(text){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(36)}
function qid(q){return 'QB-'+hashText([q.question,...q.options.map(o=>o.text),q.answer].join('|').toLowerCase().replace(/\s+/g,' '))}
function renderPreview(){const issues=[];parsed.forEach((q,i)=>{if(!q.question?.trim())issues.push(`Q${i+1}: Question missing`);if((q.options||[]).filter(o=>o.text?.trim()).length<4)issues.push(`Q${i+1}: Options missing`);if(!['A','B','C','D'].includes(q.answer))issues.push(`Q${i+1}: Answer missing`)});$('parseInfo').innerHTML=`Questions: <b>${parsed.length}</b> &nbsp; Issues: <b>${issues.length}</b>${issues.length?`<details><summary>View</summary>${issues.map(x=>`<div>${esc(x)}</div>`).join('')}</details>`:''}`;$('saveBtn').disabled=!parsed.length||issues.length>0;$('preview').innerHTML=parsed.map((q,i)=>`<div class="qcard"><b>Q${i+1}. ${esc(q.question)}</b>${q.options.map(o=>`<p>${o.key}) ${esc(o.text)} ${q.answer===o.key?'✅':''}</p>`).join('')}</div>`).join('')}
async function loadAll(){const snap=await getDocs(collection(db,'questionBank'));all=[];snap.forEach(d=>all.push({id:d.id,...d.data()}));all.sort((a,b)=>String(a.subject||'').localeCompare(String(b.subject||''))||String(a.className||'').localeCompare(String(b.className||''))||String(a.lesson||'').localeCompare(String(b.lesson||'')));fillFilters();renderList()}
function fillFilters(){const preserve={s:$('filterSubject').value,c:$('filterClass').value,l:$('filterLesson').value};const options=(arr,label)=>`<option value="">${label}</option>`+[...new Set(arr.filter(Boolean))].sort().map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');$('filterSubject').innerHTML=options(all.map(x=>x.subject),'All Subjects');$('filterClass').innerHTML=options(all.map(x=>x.className),'All Classes');$('filterLesson').innerHTML=options(all.map(x=>x.lesson),'All Lessons');$('filterSubject').value=preserve.s;$('filterClass').value=preserve.c;$('filterLesson').value=preserve.l}
function renderList(){const s=$('filterSubject').value,c=$('filterClass').value,l=$('filterLesson').value;const rows=all.filter(x=>(!s||x.subject===s)&&(!c||x.className===c)&&(!l||x.lesson===l));$('stats').innerHTML=`Total saved: <b>${all.length}</b> &nbsp; Showing: <b>${rows.length}</b>`;$('list').innerHTML=rows.map((q,i)=>`<div class="qcard"><div class="qhead"><label><input type="checkbox" class="qbSelect" value="${q.id}"> <b>${esc(q.subject||'General')} → ${esc(q.className||'General')} → ${esc(q.lesson||'General')}</b></label><button class="danger deleteOne" data-id="${q.id}">Delete</button></div><p><b>${i+1}. ${esc(q.question)}</b></p>${(q.options||[]).map(o=>`<p>${o.key}) ${esc(o.text)} ${q.answer===o.key?'✅':''}</p>`).join('')}</div>`).join('')||'<p class="msg warn">Questions levu.</p>';document.querySelectorAll('.deleteOne').forEach(b=>b.onclick=async()=>{if(confirm('Ee question delete cheyyala?')){await deleteDoc(doc(db,'questionBank',b.dataset.id));await loadAll()}})}
onAuthStateChanged(auth,u=>{if(!u)location.href='login.html';else loadAll()});$('logout').onclick=()=>signOut(auth);$('parseBtn').onclick=()=>{parsed=parseQuestions($('rawBits').value,folder($('subject').value));if(!parsed.length)return show('Questions detect avvaledu.','err');renderPreview();show(`${parsed.length} questions ready.`)};$('saveBtn').onclick=async()=>{const subject=folder($('subject').value),className=folder($('className').value),lesson=folder($('lesson').value);$('saveBtn').disabled=true;try{for(let i=0;i<parsed.length;i+=450){const wb=writeBatch(db);parsed.slice(i,i+450).forEach(q=>wb.set(doc(db,'questionBank',qid(q)),{...q,subject,className,lesson,updatedAt:serverTimestamp(),createdAt:serverTimestamp()},{merge:true}));await wb.commit()}show(`${parsed.length} questions saved ✅`);parsed=[];$('rawBits').value='';renderPreview();await loadAll()}catch(e){show(e.message,'err')}finally{$('saveBtn').disabled=false}};$('clearBtn').onclick=()=>{parsed=[];$('rawBits').value='';renderPreview()};$('loadBtn').onclick=renderList;['filterSubject','filterClass','filterLesson'].forEach(id=>$(id).onchange=renderList);$('deleteSelectedBtn').onclick=async()=>{const ids=[...document.querySelectorAll('.qbSelect:checked')].map(x=>x.value);if(!ids.length)return show('Questions select cheyyandi.','err');if(!confirm(`${ids.length} questions delete cheyyala?`))return;for(let i=0;i<ids.length;i+=450){const wb=writeBatch(db);ids.slice(i,i+450).forEach(id=>wb.delete(doc(db,'questionBank',id)));await wb.commit()}await loadAll();show('Selected questions deleted ✅')};
