let exam,student,idx=0,answers={},endAt,tick;
function init(){student=loadSession();if(!student)return block('Student details missing. Go to home page.');exam=getExams().find(e=>e.id===student.examId);if(!exam)return block('Exam not found.');let now=new Date(),st=exam.start?new Date(exam.start):null,en=exam.end?new Date(exam.end):null;if(st&&now<st)return block('Exam ఇంకా start కాలేదు. Start: '+st.toLocaleString());if(en&&now>en)return block('Exam time closed.');instName.textContent=exam.institute;examTitle.textContent=exam.title;studentInfo.innerHTML=`<b>${student.name}</b><br>${student.hall}`;let durEnd=new Date(Date.now()+exam.duration*60000);endAt=en&&en<durEnd?en:durEnd;examApp.classList.remove('hidden');renderQ();tick=setInterval(updateTimer,1000);updateTimer()}
function loadSession(){try{return JSON.parse(sessionStorage.getItem('ksr_student'))}catch(e){return null}}
function block(msg){blocked.classList.remove('hidden');blocked.innerHTML='<div class="notice danger">'+msg+'</div><a class="btn" href="index.html">Go Home</a>'}
function renderQ(){let q=exam.questions[idx];qNo.textContent=`Question ${idx+1} / ${exam.questions.length}`;qText.innerHTML=`<h3>${esc(q.question)}</h3>`;opts.innerHTML=['A','B','C','D'].map(k=>`<label class="option ${answers[idx]===k?'correct':''}"><input type="radio" name="ans" ${answers[idx]===k?'checked':''} onchange="answers[${idx}]='${k}';renderNav()"> <b>${k})</b> ${esc(q.options[k])}</label>`).join('');renderNav()}
function renderNav(){qnav.innerHTML=exam.questions.map((q,i)=>`<div onclick="idx=${i};renderQ()" class="qnum ${answers[i]?'answered':''} ${i===idx?'current':''}">${i+1}</div>`).join('')}
function nextQ(){if(idx<exam.questions.length-1)idx++;renderQ()}function prevQ(){if(idx>0)idx--;renderQ()}function clearAns(){delete answers[idx];renderQ()}function esc(s){return String(s||'').replaceAll('<','&lt;')}
function updateTimer(){let left=Math.max(0,endAt-Date.now());let m=Math.floor(left/60000),s=Math.floor((left%60000)/1000);timer.textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');if(left<=0)submitExam(true)}
function submitExam(auto){if(!auto&&!confirm('Submit exam?'))return;clearInterval(tick);let score=0,total=0,detail=[];exam.questions.forEach((q,i)=>{let ok=answers[i]===q.answer;let mk=Number(q.marks)||1;total+=mk;if(ok)score+=mk;detail.push({no:i+1,question:q.question,selected:answers[i]||'',correct:q.answer,marks:ok?mk:0})});let res={id:uid(),examId:exam.id,examTitle:exam.title,institute:exam.institute,name:student.name,hall:student.hall,score,total,percent:Math.round(score*10000/total)/100,answers,detail,submittedAt:new Date().toISOString(),timeTaken:Math.round((new Date()- (new Date(endAt-exam.duration*60000)))/1000)};let all=getResults();all.push(res);setResults(all);sessionStorage.setItem('ksr_last_result',JSON.stringify(res));location.href='result.html'}
window.onload=init;
